TEMPLATE = vcapp
TARGET = Jeu
ressources.base = image
ressources.files = image/sprites/placeHolderSprite.png
CONFIG += warn_on qt debug windows console
HEADERS += ./header/gameObject.h ./header/game.h ./header/player.h ./header/inputs.h ./header/timer.h ./header/prisonScene.h ./header/sceneManager.h ./header/baseScene.h
SOURCES += main.cpp ./src/gameObject.cpp ./src/game.cpp ./src/player.cpp ./src/timer.cpp ./src/prisonScene.cpp ./src/sceneManager.cpp ./src/baseScene.cpp
INCLUDEPATH += ./header ./src ./map ./image
map_folder.files = $$files($$PWD/map/*)
map_folder.path = $$OUT_PWD/map
INSTALLS += map_folder
RESOURCES += ressources
QT += widgets